apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.fridgeful.ocr'
version = '1.0.0'

android {
  namespace 'com.fridgeful.ocr'
  defaultConfig { versionCode 1; versionName '1.0.0' }
}

dependencies {
  implementation 'com.google.mlkit:text-recognition:16.0.1'
}
