import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const url=process.env.FRIDGEFUL_TEST_URL??'http://localhost:8081';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto(url);await page.getByText('A fresh start',{exact:true}).waitFor();
  await page.getByText('Try a demo fridge ↗',{exact:true}).click();
  await page.getByRole('button',{name:'Open Strawberries',exact:true}).click();
  await page.getByRole('button',{name:'Ate / used it',exact:true}).click();
  await page.getByRole('tab',{name:'My impact',exact:true}).click();
  await page.getByText('$4.49',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Undo Strawberries check-in',exact:true}).click();
  await page.getByText('$0.00',{exact:true}).first().waitFor();
  await page.getByRole('tab',{name:'My fridge',exact:true}).click();
  await page.getByRole('button',{name:'Open Large eggs',exact:true}).click();
  await page.getByRole('button',{name:'Ate / used 1 egg',exact:true}).click();
  await page.getByText(/11 egg · Fridge/).last().waitFor();
  await page.getByRole('button',{name:'Wasted 1',exact:true}).click();
  await page.getByText('Record food waste?',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Record waste',exact:true}).click();
  await page.getByRole('tab',{name:'My impact',exact:true}).click();
  await page.getByRole('button',{name:'Undo Large eggs check-in',exact:true}).first().click();
  await page.getByRole('button',{name:'Undo Large eggs check-in',exact:true}).first().click();
  await page.getByRole('tab',{name:'Add food',exact:true}).click();
  await page.getByText('Try a sample',{exact:true}).click();
  await page.getByRole('button',{name:'Find groceries',exact:true}).click();
  await page.getByText('Review your groceries',{exact:true}).waitFor();
  assert.equal(await page.getByRole('checkbox').count(),6);
  await page.getByRole('button',{name:'Edit Whole Milk',exact:true}).click();
  await page.getByText('Grocery details',{exact:true}).waitFor();
  await page.getByRole('textbox',{name:'Purchased on',exact:true}).fill('2026-');
  await page.getByText('Grocery details',{exact:true}).waitFor();
  const day=new Date();const date=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`;
  await page.getByRole('textbox',{name:'Purchased on',exact:true}).fill(date);
  await page.getByRole('textbox',{name:'Item name',exact:true}).fill('Receipt milk');
  await page.getByRole('button',{name:'Save grocery',exact:true}).click();
  await page.getByText('Review your groceries',{exact:true}).waitFor();
  await page.getByRole('checkbox',{name:'Include Receipt milk',exact:true}).waitFor();
  await page.getByRole('button',{name:'Add 6 groceries',exact:true}).click();
  await page.getByRole('button',{name:'Open Receipt milk',exact:true}).waitFor();
  await page.reload();await page.getByRole('button',{name:'Open Receipt milk',exact:true}).waitFor();
  await page.getByRole('button',{name:'Freezer',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:/^Open /}).count(),1);
  await page.getByRole('button',{name:'All food',exact:true}).click();
  await page.getByRole('textbox',{name:'Search food',exact:true}).fill('receipt milk');
  assert.equal(await page.getByRole('button',{name:/^Open /}).count(),1);
  await page.getByRole('tab',{name:'Add food',exact:true}).click();
  await page.getByText('Try a sample',{exact:true}).click();
  await page.getByRole('button',{name:'Find groceries',exact:true}).click();
  await page.getByText('This receipt has already been imported. Check your fridge for its groceries.',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: receipt review/edit/import, incomplete date editing, full and partial use/waste/undo, totals, reload persistence, filters, search, duplicate guard; no page errors.');
} finally {await browser.close();}
